### ISSUE TITLE
Socket hang up

### ISSUE THREAD

**Issue by harm-7** [gruijter/com.gruijter.beeclear#2] opened 2022-01-20 18:48 UTC
Hi,

I have been using the beeclear app for a long time without any issues, but recently (maybe since the last update of the app?) the device frequently becomes unavailable due to socket hang up. At first it happened infrequently but seems to happen more and more often. The error does go away but can last sometimes for hours or even a day. Rebooting homey did not help, nor reinstalling the device. Is this a known issue? Or can you help me debug?

Thanks and best regards,
-Harm

**Comment by gruijter** [comment] 2022-01-22 17:10
since version 2.0.0 the timeout depends on the polling time. Before that the timeout could be longer then the polling interval and that would lead to power values getting to Homey out of sequence. 

Timeouts could mean you have bad WiFi. It could also be caused by the Beeclear unit being overloaded. An occasional timeout is no problem, but as you said if it takes an hour or longer you have an issue.

If you increase the polling time you will also increase the timeout. What is your polling time set at? The default is 10 seconds, but depending on how you use the values it would be no problem to increase it to 30 seconds or even longer.

**Comment by gruijter** [comment] 2022-03-16 18:00
No feedbacknfrom you, so closing the issue. Please reopen if needed.

**Closed by gruijter** 2022-03-16 18:00 UTC
